---
- name: Cron Setup
  hosts: all

  tasks:
  - name: Add Cron Job
    cron:
      name: Run Test Script
      minute: 30
      hour: 9
      day: "*"
      month: "*"
      weekday: "1-5"
      user: riya
      job: /tmp/script/test.sh
      disabled: yes
